# Generated by Django 3.1.5 on 2021-04-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210407_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_width',
        ),
    ]
